BlogExample/Web/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Models
{
    public class Blog
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Picture { get; set; }
        public string Title { get; set; }
        public string Writer { get; set; }
        public string Content { get; set; }
    }
}

BlogExample/Web/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Models
{
    public class Category
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public string Name { get; set; }
    }
}

BlogExample/Web/Models/ErrorViewModel.cs
namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogExample/Web/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Web.Models;
using Web.Repository.Abstract;
using Web.Statics;

namespace Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogRepo _blogRepo;
        public BlogController(IBlogRepo blogRepo)
        {
            _blogRepo = blogRepo;
        }
        public async Task<IActionResult> GetAllBlog()
        {
            var data = await _blogRepo.GetAll(StaticDetails.GetBlogList);
           
            return View(data);
        }

     

        public async Task<IActionResult> BlogDetail(int Id)
        {
            var data = await _blogRepo.GetbyId(StaticDetails.BlogGetById, Id);
            return View(data);
        }

    }
}

BlogExample/Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Models;
using Web.Repository.Abstract;
using Web.Statics;

namespace Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepo _categoryRepo;
        public CategoryController(ICategoryRepo categoryRepo)
        {
            _categoryRepo = categoryRepo;
        }
        public async Task<IActionResult> GetAllCategory()
        {
            var data = await _categoryRepo.GetAll(StaticDetails.GetCategoryList);
            return View(data);
        }

        public async Task<IActionResult> CategoryDetail(int Id)
        {
            var data = await _categoryRepo.GetbyId(StaticDetails.GetCategoryById, Id);
            return View(data);
        }

    }
}

BlogExample/Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogExample/Web/Views/Blog/BlogDetail.cshtml
@using Web.Models
@model Blog
<div class="p-4" style="border-radius:20px;">
    <div class="row">
        <div class="col-6">
            <h2 class="text-primary">Blog Detail</h2>
        </div>
    </div>
    <br />
    <br />
    <div>
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">CategoryId</th>
                    <th scope="col">Picture</th>
                    <th scope="col">Title</th>
                    <th scope="col">Writer</th>
                    <th scope="col">Content</th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <th scope="row">@Model.Id</th>
                    <td>@Model.CategoryId</td>
                    <td>@Model.Picture</td>
                    <td>@Model.Title</td>
                    <td>@Model.Writer</td>
                    <td>@Model.Content</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

BlogExample/Web/Views/Blog/GetAllBlog.cshtml
@using Web.Models
@model IList<Blog>
<div class="p-4" style="border-radius:20px;">
    <div class="row">
        <div class="col-6">
            <h2 class="text-primary">Blog List</h2>
        </div>
    </div>
    <br />
    <br />
    <div>
        <table class="table">
            <thead class="thead-light">
                <tr>
                    
                    <th scope="col">CategoryId</th>
                    <th scope="col">Picture</th>
                    <th scope="col">Title</th>
                    <th scope="col">Writer</th>
                    <th scope="col">Content</th>
                    <th scope="col">#</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    
                    <tr> 
                        
                        <td> @item.CategoryId</td>
                        <td>@item.Picture</td>
                        <td>@item.Title</td>
                        <td>@item.Writer</td>
                        <td>@item.Content</td>
                        <td><a asp-controller="Blog" asp-action="BlogDetail" asp-route-id="@item.Id">Detail</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BlogExample/Web/Views/Category/CategoryDetail.cshtml
@using Web.Models
@model Category
<div class="p-4" style="border-radius:20px;">
    <div class="row">
        <div class="col-6">
            <h2 class="text-primary">Category Detail</h2>
        </div>
    </div>
    <br />
    <br />
    <div>
        <table class="table">
            <thead class="thead-light">
                <tr>
                    
                    <th scope="col">Blog Id</th>
                    <th scope="col">Name</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    
                    <td>@Model.BlogId</td>
                    <td>@Model.Name</td>
                    
                </tr>
            </tbody>
        </table>
    </div>
</div>

BlogExample/Web/Views/Category/GetAllCategory.cshtml
@using Web.Models
@model IList<Category>
<div class="p-4" style="border-radius:20px;">
    <div class="row">
        <div class="col-6">
            <h2 class="text-primary">Category List</h2>
        </div>
    </div>
    <br />
    <br />
    <div>
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Blog Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">#</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        
                         <td>@item.BlogId</td>
                         <td>@item.Name</td>
                         <td><a asp-controller="Category" asp-action="CategoryDetail" asp-route-id="@item.Id">Detail</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BlogExample/Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BlogExample/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Blog" asp-action="GetAllBlog">All Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Category" asp-action="GetAllCategory">All Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>